### ISSUE TITLE
Table features

### ISSUE THREAD

**Issue by abhigudi** [gnusiva/pro1#9]
Hi Siva 

Please find the details along with the json struture for the table 

1. First row to be a checkbox --- Check on this on top header of the table we get a button drop down which will be having the action provided in the supportedAction field of the json.
2. The last column is the supportedAction field which will be represented by vertical three dots.
3.Pagination data also will be present in the json provided for the table.,
4.Table will be key value pair with the column names in the json
5.Some rows will be link where the link is also provided by the json

`{
  "jsonapi": {
    "version": "1.0"
  },
  "meta": {
    "copyright": "XXXXXX"
  },
  "data": {
    "type": "Supplier Invites To Approve",
    "status": "success",
    "id": null,
    "items": [
      {
        "taskId": 163702,
        "taskName": "Approve supplier(Purchasing)",
        "taskDescription": null,
        "supplierName": "XXXXX",
        "relationshipId": 464065,
        "customerId": 50,
        "invitedBy": "XXXXXX@XXXXX.com",
        "inviteStatus": "Pre-invited",
        "supplierStatus": null,
        "inviteJustification": null,
        "division": "01.01.020       ",
        "lavanteUID": 450327,
        "supplierErpId": null,
        "invitationID": 429524,
        "profileCompletedOn": null,
        "fieldName": null,
        "operationType": null,
        "oldValue": null,
        "newValue": null,
        "createdBy": null,
        "assignedAt": "07/17/2018, 03:13 AM PDT",
        "assignedTo": "ABC",
        "trackChangesID": null,
        "trackChangesCustomFieldsID": null,
        "trackChangesMultiFieldsID": null,
        "trackChangesCFEID": null,
        "workflowProcessDetailsID": null,
        "actualOwner": null,
        "workflowTypeID": null,
        "modifiedBy": null,
        "modifiedOn": null,
        "workflowDesc": null,
        "currentStateID": null,
        "previousStateID": null,
        "approvalHistory": null,
        "supportedAction": {
          "sendEmail": true,
          "editProfile": true,
          "reject": true,
          "approve": true,
          "reassign": true
        },
        "taskStatus": "Ready",
        "supErpId": null
      }
    ],
    "filters": null,
    "options": null,
    "message": null,
    "note": null,
    "bannerMessage": null,
    "pagination": {
      "totalRecords": 17,
      "pageSize": 20,
      "pageNumber": 1
    },
    "sort": {
      "order": null,
      "column": null
    },
    "links": {
      "supplierName": "viewSupplierProfile.lvp?redirectURL=viewCompanyDetails&supplierId=",
      "approvalHistory": "viewSupplierProfile.lvp?redirectURL=viewStatusProfileStageHistory&supplierId=",
      "invitationID": "viewSupplierProfile.lvp?pageRefreshURL=viewOnboarding.lvp&inviteID="
    },
    "menus": null,
    "disableAdd": false,
    "column": null
  },
  "callback": null,
  "error": null
}`

**Comment by gnusiva** [comment]
All five points above mentionded were done and pushed

**Comment by abhigudi** [comment]
1. Action should be primng dropdown button
2. Should not remove option from the list of actions instead should be disabled.
3. Dropdown should be a different component and table a different and the selection and actions should be handled in the controller.
4. The json should be a service,so could you please write a service for the same.
5. pagination  implementation is missing.
